/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** アプリケーションのヘルスチェック */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * デモクイズの取得
         * @description デモ用のクイズデータを返します
         */
        get: operations["DemoController_getQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スキルクイズの取得
         * @description ランダムなサーヴァントのスキル情報を含むクイズデータを返します
         */
        get: operations["QuizController_getSkillQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servants/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * サーヴァント選択肢一覧の取得
         * @description クイズで使用するサーヴァントの選択肢データを取得します。各サーヴァントのID、名前、オリジナル名が含まれます。
         */
        get: operations["ServantsController_getServantOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NoblePhantasm: {
            /**
             * @description ノーブルファンタズムID
             * @example 101
             */
            id: number;
            /**
             * @description ノーブルファンタズム番号
             * @example 1
             */
            num: number;
            /**
             * @description カードタイプ
             * @example buster
             */
            card: string;
            /**
             * @description ノーブルファンタズム名
             * @example 約束された勝利の剣
             */
            name: string;
            /**
             * @description オリジナル名
             * @example Excalibur
             */
            originalName: string;
            /**
             * @description ルビ
             * @example エクスカリバー
             */
            ruby: string;
            /** @description アイコンURL */
            icon: string;
            /**
             * @description ランク
             * @example A++
             */
            rank: string;
            /**
             * @description タイプ
             * @example 対城宝具
             */
            type: string;
            /** @description 効果フラグ */
            effectFlags: string[];
            /** @description 詳細説明 */
            detail: string;
            /** @description 未修正の詳細説明 */
            unmodifiedDetail: string;
        };
        Skill: {
            /**
             * @description スキルID
             * @example 501
             */
            id: number;
            /**
             * @description スキル番号
             * @example 1
             */
            num: number;
            /**
             * @description スキル名
             * @example カリスマ
             */
            name: string;
            /**
             * @description オリジナル名
             * @example Charisma
             */
            originalName: string;
            /** @description ルビ */
            ruby: string;
            /** @description スキル詳細説明 */
            detail: string;
            /** @description 未修正のスキル詳細説明 */
            unmodifiedDetail: string;
            /** @description スキルタイプ */
            type: string;
            /**
             * @description 優先度
             * @example 0
             */
            priority: number;
            /** @description アイコンURL */
            icon: string;
        };
        ServantDetailGetResponseDto: {
            /**
             * @description サーヴァントID
             * @example 1
             */
            id: number;
            /**
             * @description コレクション番号
             * @example 1
             */
            collectionNo: number;
            /**
             * @description サーヴァント名
             * @example アルトリア・ペンドラゴン
             */
            name: string;
            /**
             * @description オリジナル名
             * @example Artoria Pendragon
             */
            originalName: string;
            /** @description ルビ */
            ruby: string;
            /**
             * @description クラスID
             * @example 1
             */
            classId: number;
            /**
             * @description レア度
             * @example 5
             */
            rarity: number;
            /** @description ノーブルファンタズム一覧 */
            noblePhantasms: components["schemas"]["NoblePhantasm"][];
            /** @description スキル一覧 */
            skills: components["schemas"]["Skill"][];
        };
        ServantsOptions: {
            /**
             * @description サーヴァントID
             * @example 1
             */
            id: number;
            /**
             * @description サーヴァント名
             * @example アルトリア・ペンドラゴン
             */
            name: string;
            /**
             * @description オリジナル名
             * @example Artoria Pendragon
             */
            originalOverwriteName: string;
            /**
             * @description クラスID
             * @example 1
             */
            classId: number;
        };
        ServantsOptionsGetResponseDto: {
            /** @description サーヴァント選択肢の配列 */
            options: components["schemas"]["ServantsOptions"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アプリケーションの状態を返します */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    DemoController_getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description デモクイズデータ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    QuizController_getSkillQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スキルクイズデータ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServantDetailGetResponseDto"];
                };
            };
        };
    };
    ServantsController_getServantOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サーヴァント選択肢一覧の取得に成功しました */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServantsOptionsGetResponseDto"];
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
